global:
  resolve_timeout: 5m

route:
  receiver: discord
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h

receivers:
  - name: discord
    discord_configs:
      - webhook_url: "https://discord.com/api/webhooks/1234567890/abcdefghijklmnopqrstuvwxyz"
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "instance"]
