global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - alertmanager:9093
rule_files:
  - /etc/prometheus/alert_rules.yml
scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100
